# Generated by Django 2.2 on 2018-08-19 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sutra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=3, verbose_name='Section')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_sutra', to='book.Book')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_sutra', to='book.Chapter')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_sutra', to='post.Post')),
            ],
            options={
                'db_table': 'sutra',
            },
        ),
        migrations.CreateModel(
            name='CommentSutra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor_sutra', to=settings.AUTH_USER_MODEL, verbose_name='Commentor')),
                ('commentsutra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsutra_commentsutra', to='sutra.CommentSutra')),
                ('sutra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sutra_commentsutra', to='sutra.Sutra')),
            ],
            options={
                'db_table': 'comment_sutra',
            },
        ),
    ]
