# Generated by Django 2.2 on 2018-06-08 03:35

import avatar.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar/default.png', upload_to=avatar.models.uploadAvatar)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(related_name='user_avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'avatar',
            },
        ),
    ]
