# Generated by Django 2.2 on 2018-06-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avatar',
            table='avatar_avatar',
        ),
    ]
