# Generated by Django 2.2 on 2018-08-15 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=10, unique=True, verbose_name='Book')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=10, verbose_name='Chapter')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_chapter', to='book.Book')),
            ],
            options={
                'db_table': 'chapter',
                'get_latest_by': 'timestamp',
            },
        ),
    ]
