# Generated by Django 2.2 on 2018-06-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('book', '0001_initial'),
        ('sutra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sutra',
            name='post_ptr',
        ),
        migrations.RemoveField(
            model_name='sutra',
            name='title',
        ),
        migrations.AddField(
            model_name='sutra',
            name='blog_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sutra',
            name='book',
            field=models.ManyToManyField(related_name='book_sutra', to='book.Book'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
